WARNING  glidein_config not defined () in singularity_lib.sh. Some functions like advertise and error_gen will be limited.
WARNING  String '/execute/dir_' in X509_USER_PROXY (/var/condor/execute/dir_27205/glide_Tff0jm/ticket/myproxy), the conversion to run in Singularity may be incorrect
WARNING  String '/execute/dir_' in X509_USER_CERT (/var/condor/execute/dir_27205/glide_Tff0jm/hostcert.pem), the conversion to run in Singularity may be incorrect
WARNING  String '/execute/dir_' in X509_USER_KEY (/var/condor/execute/dir_27205/glide_Tff0jm/hostkey.pem), the conversion to run in Singularity may be incorrect
WARNING  String '/execute/dir_' in _CONDOR_EXECUTE (/var/condor/execute/dir_27205/glide_Tff0jm/execute), the conversion to run in Singularity may be incorrect
WARNING  String '/execute/dir_' in OSG_WN_TMP (/var/condor/execute/dir_27205), the conversion to run in Singularity may be incorrect
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/crumbs/get_successful_simulations_rowids.py", line 46, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/crumbs/get_successful_simulations_rowids.py", line 42, in main
    return get_successful_simulations_rowids(options.database, options.table)
  File "/usr/local/lib/python3.8/dist-packages/crumbs/get_successful_simulations_rowids.py", line 25, in get_successful_simulations_rowids
    cursor.execute("SELECT rowid, * FROM quetzal_EGG_1 WHERE newicks <> '';")
sqlite3.OperationalError: no such table: quetzal_EGG_1
